name: tagpr

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "labeled", "unlabeled" ]

jobs:
  tagpr:
    runs-on: ubuntu-24.04
    if: >
      ${{
        github.event_name == 'push'
        || (
          github.event_name == 'pull_request'
          && github.event.sender.type != 'Bot'
          && github.event.action == 'labeled'
          && contains(fromJSON('["major","minor"]'), github.event.label.name)
          && github.event.pull_request.merged == true
        )
        || (
          github.event_name == 'pull_request'
          && github.event.sender.type != 'Bot'
          && contains(fromJSON('["tagpr:major","tagpr:minor"]'), github.event.label.name)
          && startsWith(github.event.pull_request.head.ref, 'tagpr-from-')
        )
      }}
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.TAGPR_APP_ID }}
          private-key: ${{ secrets.TAGPR_PRIVATE_KEY }}

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: "main"
          token: ${{ steps.generate_token.outputs.token }}

      # for update lockfiles
      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - uses: Songmu/tagpr@b3fb89424646b06c8aa460f50307c60b6a541425 # v1.17.1
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
