name: tagpr

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ "labeled", "unlabeled" ]

jobs:
  tagpr:
    runs-on: ubuntu-24.04
    if: >
      github.event_name == 'push'
      || (
        github.event_name == 'pull_request'
        && github.event.sender.type != 'Bot'
        && github.event.action == 'labeled'
        && contains(fromJSON('["major","minor"]'), github.event.label.name)
        && github.event.pull_request.merged == true
      )
      || (
        github.event_name == 'pull_request'
        && github.event.sender.type != 'Bot'
        && contains(fromJSON('["tagpr:major","tagpr:minor"]'), github.event.label.name)
        && startsWith(github.event.pull_request.head.ref, 'tagpr-from-')
      )
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.TAGPR_APP_ID }}
          private-key: ${{ secrets.TAGPR_PRIVATE_KEY }}

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: "main"
          token: ${{ steps.generate_token.outputs.token }}

      # for updateLocks
      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'zulu'
          java-version: 21
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

      - uses: Songmu/tagpr@da82ed6743aec90049892070edd5561335904a9e # v1.17.0
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
